export const GET_BROTHERS = 'GET_BROTHERS';
export const GET_BROTHER_BY_KEY = 'GET_BROTHER_BY_KEY';
export const GET_FULLTIMES = 'GET_FULLTIMES';
export const GET_INTERNSHIPS = 'GET_INTERNSHIPS';

export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAILURE = 'POST_FAILURE';
