export const GET_BROTHERS_ATTEMPT = 'GET_BROTHERS_ATTEMPT';
export const GET_BROTHERS_SUCCESS = 'GET_BROTHERS_SUCCESS';
export const GET_BROTHERS_FAILURE = 'GET_BROTHERS_FAILURE';

export const GET_BROTHER_BY_KEY_ATTEMPT = 'GET_BROTHER_BY_KEY_ATTEMPT';
export const GET_BROTHER_BY_KEY_SUCCESS = 'GET_BROTHER_BY_KEY_SUCCESS';
export const GET_BROTHER_BY_KEY_FAILURE = 'GET_BROTHER_BY_KEY_FAILURE';

export const GET_FULLTIMES_ATTEMPT = 'GET_FULLTIMES_ATTEMPT';
export const GET_FULLTIMES_SUCCESS = 'GET_FULLTIMES_SUCCESS';
export const GET_FULLTIMES_FAILURE = 'GET_FULLTIMES_FAILURE';

// export const GET_INTERNSHIPS_ATTEMPT = 'GET_INTERNSHIPS_ATTEMPT';
// export const GET_INTERNSHIPS_SUCCESS = 'GET_INTERNSHIPS_SUCCESS';
// export const GET_INTERNSHIPS_FAILURE = 'GET_INTERNSHIPS_FAILURE';

export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAILURE = 'POST_FAILURE';
