export const GET_BROTHERS = 'GET_BROTHERS';
export const GET_BROTHER_BY_KEY = 'GET_BROTHER_BY_KEY';
export const GET_FULLTIMES = 'GET_FULLTIMES';
export const GET_INTERNSHIPS = 'GET_INTERNSHIPS';

export const POST_REGFORM_SUCCESS = 'POST_REGFORM_SUCCESS';
export const POST_REGFORM_FAILURE = 'POST_REGFORM_FAILURE';
export const POST_COFFEE_CHAT_FORM_SUCCESS = 'POST_COFFEE_CHAT_FORM_SUCCESS';
export const POST_COFFEE_CHAT_FORM_FAILURE = 'POST_COFFEE_CHAT_FORM_FAILURE';
export const POST_APPLICATION_SUCCESS = 'POST_APPLICATION_SUCCESS';
export const POST_APPLICATION_FAILURE = 'POST_APPLICATION_FAILURE';
